# 파이토치 딥러닝

## 선형회귀로 대략적인 구조 파악

1. regression : y=wx+b 라고 할 때 y가 종속변수, x 독립변수
    1) 인과성
    2) 연관성
    
    삼성종가 = w1 * 거래금액 + w2 * 공포지수 + w3 * 감가상각비 + b

2. curve fitting : 데이터의 패턴을 수학적 모델에 잘 입히는게 관점

In [ ]:
# 사람 5명이고 feature(키, 몸무게)가 2개, 정답값이 2개 예측(multi prediction).칼로리, 나이
x_train = [[170,65],
           [185,70],
           [175,63],
           [150,40],
           [160,50],]

y_train = [[1300, 32],
           [1550, 22],
           [1250, 25],
           [1250, 23],
           [1450, 40],
           ]

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(42)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [7]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [8]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01) # 아담W보다 스톡캐스틱 쓰는 이유는 속도 때문.

In [19]:
epochs = 100
for epoch in range(epochs + 1):
    optimizer.zero_grad()
    predict = x_train * W + b
    cost = torch.mean((predict - y_train)**2)
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0 :
        print(f'Epoch {epoch:4d}/{epochs} W: {W.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')

Epoch    0/100 W: 1.941, b: 0.134 Cost: 0.002593
Epoch  100/100 W: 1.954, b: 0.105 Cost: 0.001602


# 실습

In [105]:
""" 
"전일종가, 당일고가, 당일저가 "로 "당일주가 예측"
데이터는 아래 7개 직접 전일종가, 당일고가, 당일저가, 당일주가 수집.
삼성전자
NAVER
현대로템
LS
에코프로
현대차
SK하이닉스
"""
torch.manual_seed(1)

SAMSUNG = [87800,88000,87300]
NAVER = [170700,176800,169700]
HDLT = [29350,42900,39700]
LS = [138400,156500,138800]
ECOPRO = [101200, 104000, 99500]
HDC = [274500,277500,272500]
SKH = [238500, 238500, 234000]

x_train = torch.FloatTensor([[SAMSUNG], [NAVER], [HDLT], [LS], [ECOPRO], [HDC], [SKH]])
y_train = torch.FloatTensor([[87500], [176700], [42450], [152500], [99600], [275500], [235000]])

W = torch.zeros(3, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

epochs = 100
for epoch in range(epochs + 1):
    optimizer.zero_grad()
    # 선형회귀 모델
    predict = x_train * W + b
    # cost 계산 (Mean Square Error)
    cost = torch.mean((predict - y_train) ** 2)
    # cost로 모델 개선
    cost.backward() # cost를 기반으로 미분 계산
    optimizer.step() # 오차역전파법 실행
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print(
            f'Epoch {epoch:4d}/{epochs} W: {W[0]}, {W[1]}, {W[0]} b: {b.item():.3f} Cost: {cost.item():.6f}'
            )

Epoch    0/100 W: 151360704.0, 157725280.0, 151360704.0 b: 3055.000 Cost: 29283258368.000000
Epoch  100/100 W: nan, nan, nan b: nan Cost: nan


# 6day 숙제 (오답 ㅜㅜ)

비트코인, 솔라나, 도지코인, 리플, 페페코인 에 대하여

해당코인현재가(Y) 해당코인전일가(X1) 해당코인저가(X2) 해당코인코가(X3) NVIDIA현재주가(X4)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
# 전일종가, 당일저가, 당일고가, 앤비디아주가
BITCOIN = [82043000, 81351000, 83825000, 181939]
SOLANA = [196800, 196300, 205800, 181939]
DOZICOIN = [152, 150, 156, 181939]
RIPPLE = [610, 608, 622, 181939]
PEPECOIN = [0.02, 0.02, 0.02, 181939]

x_train = torch.FloatTensor([[BITCOIN],[SOLANA],[DOZICOIN],[RIPPLE],[PEPECOIN]])
y_train = torch.FloatTensor([[82601000], [202200], [153], [621], [0.02]])


W = torch.zeros(4, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

epochs = 100
for epoch in range(epochs + 1):
    optimizer.zero_grad()
    # 선형회귀 모델
    predict = x_train * W + b
    # cost 계산 (Mean Square Error)
    cost = torch.mean((predict - y_train) ** 2)
    # cost로 모델 개선
    cost.backward() # cost를 기반으로 미분 계산
    optimizer.step() # 오차역전파법 실행
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print(
            f'Epoch {epoch:4d}/{epochs} W: {W[0]}, {W[1]}, {W[2]} {W[3]} b: {b.item():.3f} Cost: {cost.item():.6f}'
            )

